### ISSUE TITLE
about "&" some question

### ISSUE THREAD

**Issue by NominationP** [familyld/Coding_Interviews#1]
Hi you! I have some question , sorry to disturb you !

https://github.com/familyld/Coding_Interviews/blob/master/C%2B%2B/07_QueueWithTwoStacks/Queue.h

line : 42 
T& top = stack1.top();

why need add '&' 
I try to delete it , change to :  T top = stack1.top();
it's work too.

**Comment by familyld** [comment]
Hi~ Here "&" is used to declare a reference of the variable stored in stack1.top().
Using reference won't create new variable and hence save space.
Not using "&" is OK, but using it is better.
See more on "https://www.hermetic.ch/cfunlib/ast_amp2.htm".

**Comment by NominationP** [comment]
clear ! thank you !
